spring:
  application:
    name: country-service
    third-party-api: https://restcountries.com/v3.1/name/
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true