spring:
  application:
    name: covid-service
    third-party-api: https://coronavirus-19-api.herokuapp.com/countries/
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true